// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_hIarNKIggG-WExty0HA-cQWdPp8OEjo',
    appId: '1:676263895580:web:701877bb1c88a8b79f35d9',
    messagingSenderId: '676263895580',
    projectId: 'sayittome-app',
    authDomain: 'sayittome-app.firebaseapp.com',
    storageBucket: 'sayittome-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpVBTbjnYA1Fp8D5-KlxNIB6cvjRKwGGE',
    appId: '1:676263895580:android:9d08b3beb6e4037d9f35d9',
    messagingSenderId: '676263895580',
    projectId: 'sayittome-app',
    storageBucket: 'sayittome-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8WKdjOMCD8SADdr_bzftwqO8AthftdUA',
    appId: '1:676263895580:ios:07310873e92c8b2c9f35d9',
    messagingSenderId: '676263895580',
    projectId: 'sayittome-app',
    storageBucket: 'sayittome-app.firebasestorage.app',
    iosBundleId: 'com.example.sayittome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8WKdjOMCD8SADdr_bzftwqO8AthftdUA',
    appId: '1:676263895580:ios:07310873e92c8b2c9f35d9',
    messagingSenderId: '676263895580',
    projectId: 'sayittome-app',
    storageBucket: 'sayittome-app.firebasestorage.app',
    iosBundleId: 'com.example.sayittome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_hIarNKIggG-WExty0HA-cQWdPp8OEjo',
    appId: '1:676263895580:web:6a3430c939ea22909f35d9',
    messagingSenderId: '676263895580',
    projectId: 'sayittome-app',
    authDomain: 'sayittome-app.firebaseapp.com',
    storageBucket: 'sayittome-app.firebasestorage.app',
  );
}
