import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const ctx=fs.readFileSync(path.join(root,"src/contexts/AnonMatchContext.tsx"),"utf8");
const start=ctx.indexOf("if (caller.isRegisteredProfile) {",ctx.indexOf("// Selecting an anonymous Shuffle card"));
const stop=ctx.indexOf("if (searchSessionActiveRef.current) {",ctx.indexOf("return;\n        }",start)+12);
assert(start>0,"arrival registered handler exists");
const branch=ctx.slice(start,ctx.indexOf("if (searchSessionActiveRef.current) {\n          // Cancel the earlier discovery",start));
assert.doesNotMatch(branch,/router\.(push|replace)\(\s*["\x27]\/shuffle["\x27]\s*\)/,"arrival CTA must never navigate back to Shuffle");
assert.match(branch,/targetAnonIdRef\.current = wanted/,"target must be bound to arrival anonymous");
assert.match(branch,/await startSearchSession\(\)/,"registered caller must actually send request");
assert.match(branch,/pending\?\.targetAnonId === wanted && pending\?\.solicitudId/,"only verified request may report invited");
assert.match(ctx,/router\.push\(`\/chat\/\$\{encodeURIComponent\(String\(json\.chatId\)\)\}`\)/,"anon caller still navigates to direct chat");
const toast=fs.readFileSync(path.join(root,"src/components/anonMatch/AnonArrivalToast.tsx"),"utf8");
assert.match(toast,/registeredViewer\?"INVITAR":"ABRIR"/,"registered CTA must promise an invitation, not immediate chat");
assert.match(toast,/registeredViewer\?"Tocá para invitarlo a conversar"/);
assert.match(toast,/setTimeout\(\(\)=>setArrival\(null\),5000\)/,"5s timeout remains");
console.log("PASS arrival profile click stays on current screen; registered invitation confirmed by server; anon direct chat unchanged");