import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const api=await import(pathToFileURL(path.join(root,"src/lib/anonMatch/anonArrival.ts")).href);
const now=Date.parse("2026-10-09T23:45:00.000Z");
assert.equal(api.isNewAnonymousArrival({nowMs:now}),true,"brand new");
assert.equal(api.isNewAnonymousArrival({nowMs:now,priorLastSeenAt:new Date(now-90000).toISOString(),priorAnnouncedAt:new Date(now-90000).toISOString()}),false,"heartbeat ignored");
assert.equal(api.isNewAnonymousArrival({nowMs:now,priorLastSeenAt:new Date(now-3600000).toISOString(),priorAnnouncedAt:new Date(now-3600000).toISOString()}),true,"re-entry after long absence");
assert.equal(api.isNewAnonymousArrival({nowMs:now,priorLastSeenAt:new Date(now-3600000).toISOString(),priorSessionClosed:true,priorAnnouncedAt:new Date(now-30000).toISOString()}),true,"explicitly closed session returning must alert again");
assert.equal(api.isAnonArrivalGloballyVisible({paises:["AR"]}),false,"restrict country privacy");
assert.equal(api.isAnonArrivalGloballyVisible({provincias:["Cordoba"]}),false,"restrict province privacy");
assert.equal(api.isAnonArrivalGloballyVisible({doNotDisturb:true}),false,"DND privacy");
assert.equal(api.isAnonArrivalGloballyVisible({paises:[],provincias:[]}),true,"public eligible");
assert.equal(api.isAnonArrivalAlias("anon_Ab32k987"),true);
assert.equal(api.isAnonArrivalAlias("profile_admin"),false);
const label=api.anonArrivalPublicLabel("anon_Ab32k987");
assert.match(label,/^[0-9A-Z]{7}$/);
assert.equal(api.anonArrivalPublicLabel("anon_Ab32k987"),label);
const route=fs.readFileSync(path.join(root,"src/app/api/anonymous-presence/route.ts"),"utf8");
assert.match(route,/if \(arrival\.mayAnnounce\)/);
assert.match(route,/anon_arrival_announcements/);
const visitor=fs.readFileSync(path.join(root,"src/app/api/shuffle/route.ts"),"utf8");
assert.match(visitor,/enteredAt: fieldString\(fields, "enteredAt"\)/);
const component=fs.readFileSync(path.join(root,"src/components/anonMatch/AnonArrivalToast.tsx"),"utf8");
assert.match(component,/setTimeout\(\(\)=>setArrival\(null\),5000\)/);
assert.match(component,/onSnapshot\(doc\(db,"anon_arrival_announcements","latest"\)/,"realtime listener replaces polling");
assert.match(component,/if\(!loggedIn\|\|document\.hidden\)return/,"hidden tabs do not read presence announcements");
assert.match(component,/document\.addEventListener\("visibilitychange",connect\)/,"reconnects on foreground");
assert.doesNotMatch(component,/POLL_MS|visitors=1/,"no global API polling per viewer");
assert.match(component,/api\/anon-match\/arrival-target/,"click checks live target");
assert.match(component,/source:"arrival"/,"click uses real chat system");
assert.match(component,/sayittome:anon-direct-target-request/);
const routing=fs.readFileSync(path.join(root,"src/contexts/AnonMatchContext.tsx"),"utf8");
assert.match(routing,/router\.push\(`\/chat\/\$\{encodeURIComponent\(String\(json\.chatId\)\)\}`\)/,"anonymous click navigates to real chat");
assert.match(routing,/notifyArrival\("opened"\)/,"handler confirms successful navigation");
const preflight=fs.readFileSync(path.join(root,"src/app/api/anon-match/arrival-target/route.ts"),"utf8");
assert.match(preflight,/if \(!caller\.isAnonymous\)/,"registered arrival preflight returns direct chat identity");
assert.match(preflight,/visitorChatId/,"server returns Shuffle's visitorChatId");
assert.match(component,/await openVisitorChat\(router,visitorChatId,id\)/,"registered arrival opens the SAME chat as Shuffle");
assert.doesNotMatch(component,/INVITAR|invitarlo a conversar/,"arrival CTA opens direct chats without invitation");
assert.match(routing,/if \(!arrivalClick\) window\.alert/,"arrival failures use in-app status, not unrelated alert");
console.log("PASS ANON_ARRIVAL: realtime notifications, 5s toast, hidden-tab cost pause, verified click, consent, offline states");