const assert=require("node:assert/strict");
const fs=require("node:fs");
const vm=require("node:vm");
const ts=require("typescript");
const file=fs.readFileSync("functions/src/anonDirectPush.ts","utf8");
const match=file.match(/export function anonDirectPushPresenceFresh\([\s\S]*?\n\}/);
assert.ok(match,"push freshness function exists");
const compiled=ts.transpileModule(match[0],{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
const mod={exports:{}};
vm.runInNewContext(compiled,{exports:mod.exports,module:mod,Date,String,Number});
const check=mod.exports.anonDirectPushPresenceFresh;
const time=Date.parse("2026-10-09T13:00:00Z");
const base={authUid:"uidA",source:"anon_match_presence",lastSeenAt:new Date(time-2000).toISOString(),expiresAt:new Date(time+10800000).toISOString(),chatActualId:""};
assert.equal(check(base,"uidA","chat-x",time),true,"open anon receives push");
assert.equal(check({...base,sessionClosed:true},"uidA","chat-x",time),false,"closed session never receives push");
assert.equal(check({...base,sessionClosed:true,lastSeenAt:new Date(time).toISOString()},"uidA","chat-x",time),false,"closed even with fresh lastSeen");
assert.equal(check({...base,sessionClosed:false,lastSeenAt:new Date(time-200000).toISOString()},"uidA","chat-x",time),false,"3h Shuffle card not equal active for push");
assert.equal(check({...base,authUid:"uidOther"},"uidA","chat-x",time),false,"uid-bound push");
assert.equal(check({...base,chatActualId:"other-chat"},"uidA","chat-x",time),false,"chat-specific binding");
assert.equal(check({...base,expiresAt:new Date(time-100).toISOString()},"uidA","chat-x",time),false,"expired");
console.log("PASS ANON OFFLINE PUSH: closed sessions have no push even with fresh presence; stale 3h card no push; uid and chat binding intact; zero additional Firestore reads.");
