import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath,pathToFileURL} from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const component=fs.readFileSync(path.join(root,"src/components/anonMatch/AnonArrivalToast.tsx"),"utf8");
const router=fs.readFileSync(path.join(root,"src/lib/shuffle/shuffleVisitorNavigation.ts"),"utf8");
const preflight=fs.readFileSync(path.join(root,"src/app/api/anon-match/arrival-target/route.ts"),"utf8");
const ctx=fs.readFileSync(path.join(root,"src/contexts/AnonMatchContext.tsx"),"utf8");
assert.match(component,/if \(auth\.currentUser\?\.isAnonymous === false\)/,"registered user branches to direct chat");
assert.match(component,/await openVisitorChat\(router,visitorChatId,id\)/,"arrival shares Shuffle card chat navigation");
assert.match(component,/visitorChatId=String\(result\.visitorChatId/,"server-backed visitor identity");
assert.match(component,/source:"arrival"/,"anonymous visitors still use anon-direct pathway");
assert.doesNotMatch(component,/INVITAR|invitarlo a conversar/,"no invitation UI");
assert.match(component,/Tocá para empezar a hablar/);
assert.match(preflight,/pickAvailableMatchTarget/,"still checks live availability and audience");
assert.match(preflight,/lookupAnonMatchAliasBinding/,"validates bound anonymous target");
assert.match(preflight,/getAnonMatchAdminDoc\("anonimos_activos", anonId\)/,"trusted presence read");
assert.match(preflight,/sanitizeShuffleVisitorChatId\(livePresence\.chatSessionId\)/,"uses exact Shuffle visitorChatId, never arbitrary body");
assert.match(preflight,/visitorChatId/,"registered receives direct visitor id");
assert.match(router,/buildProfileAnonChatId\(visitorId, username\)/,"profile uses established profile-anon thread id");
assert.match(router,/&anonPeer=1/,"visitor Chat page route keeps anon peer flag");
assert.match(router,/return true;/,"navigation returns success for alert handler");
assert.match(ctx,/router\.push\(`\/chat\/\$\{encodeURIComponent\(String\(json\.chatId\)\)\}`\)/,"anon-to-anon still opens direct");
const {buildProfileAnonChatId}=await import(pathToFileURL(path.join(root,"src/lib/chat/anonChatId.ts")).href);
const recipient="anon_visit0r123";const username="registered_qa";
assert.equal(buildProfileAnonChatId(recipient,username),recipient+"__anon_to__"+username,"same stable thread as Shuffle");
console.log("PASS arrival DIRECT registered->anon reuses Shuffle profile-chat, verified server identity, no invite, anon->anon unaffected");