const assert = require("node:assert/strict");
const fs = require("node:fs");
function src(p){return fs.readFileSync(p,"utf8");}
const swipe=src("src/components/chat/ChatSwipeRevealTime.tsx");
const p=swipe.match(/function onPointerDown[\s\S]*?\n  \}/)?.[0]||"";
assert.ok(p && !p.includes("setPointerCapture"),"tap must not be captured by swipe");
assert.match(swipe,/axisRef\.current === "y"/);
assert.match(swipe,/if \(!event\.currentTarget\.hasPointerCapture\(event\.pointerId\)\)/);
const viewer=src("src/components/chat/media/FullscreenMedia.tsx");
assert.match(viewer,/data-fullscreen-media-viewer="1"/);
assert.match(viewer,/data-media-zoom-controls="1"/);
assert.match(viewer,/aria-label="Ampliar imagen"/);
assert.match(viewer,/aria-label="Reducir imagen"/);
assert.match(viewer,/controls=\{!secure\}/,"secure video must not have native download controls");
assert.match(viewer,/disablePictureInPicture=\{secure\}/);
const profile=src("src/components/chat/ProfileAnonChat.tsx");
assert.match(profile,/aria-label="Abrir video a pantalla completa"/);
assert.match(profile,/setFullscreenMediaType\("video"\)/);
assert.match(profile,/onClick=\{\(\) => \{[\s\S]*?setFullscreenMediaType\("video"\)/);
const anon=src("src/components/anonMatch/AnonDirectChatWindow.tsx");
assert.match(anon,/aria-label="Abrir video a pantalla completa"/);
assert.match(anon,/onClick=\{\(\) => onOpenMedia\(message\.mediaUrl \|\| "", "video"\)\}/);
assert.match(anon,/onClick=\{\(\) => onOpenBomb\(message\)\}/);
const admin=src("src/components/admin/spectator/AdminAnonMatchChatsPanel.tsx");
const route=src("src/app/api/admin/anon-match-chats/route.ts");
assert.match(admin,/AdminSpectatorMessageContent/);
assert.match(admin,/rawMessageId \|\| msg\.id/);
assert.match(route,/sourceChatId: sourceDoc\.id/);
assert.match(route,/rawMessageId: row\.id/);
assert.match(route,/await verifyAdminIdToken\(req\)/);
assert.match(admin,/5 \* 60_000/);
console.log("PASS CHAT MEDIA VIEWERS: tap preserved under horizontal swipe; photo zoom; video fullscreen both chat types; bomb click; no native download controls for secure; admin media uses verified read-only existing endpoint.");
