const fs=require('node:fs'),assert=require('node:assert/strict');
const stories=fs.readFileSync('src/components/stories/StoriesBootstrap.tsx','utf8');
const shuffle=fs.readFileSync('src/app/api/shuffle/route.ts','utf8');
const admin=fs.readFileSync('src/components/admin/spectator/AdminAnonMatchChatsPanel.tsx','utf8');
const usage=fs.readFileSync('src/app/api/usage/ping/route.ts','utf8');
assert.match(stories,/STORIES_QUIET_REFRESH_MS = 60_000/);
assert.match(stories,/STORIES_CHAT_REFRESH_MS = 3 \* 60_000/);
assert.match(stories,/refreshStoriesIndex\(viewerKey, quietRefresh\)/);
assert.match(stories,/\}, refreshIntervalMs\)/);
assert.match(stories,/!documentHidden/);
assert.match(shuffle,/if \(profileScanInFlight\) return profileScanInFlight/);
assert.match(shuffle,/if \(visitorScanInFlight\) return visitorScanInFlight/);
assert.match(shuffle,/visitorScanInFlight === pending\) visitorScanInFlight = null/);
assert.match(shuffle,/profileScanInFlight === pending\) profileScanInFlight = null/);
assert.match(shuffle,/const VISITOR_CACHE_MS = 20_000;/);
assert.match(admin,/setInterval\(refresh, 60_000\)/);
assert.match(admin,/setInterval\(\(\) => void loadDetail\(true\), 15_000\)/);
assert.match(admin,/if \(inFlight \|\| document.hidden\) return;/);
assert.ok(!usage.includes('limit(500)'));
console.log('PASS_FIRESTORE_READ_EFFICIENCY_GATES: stories_60s_chat_180s, singleton_scan, admin_throttle, usage_scan_removed');
