import assert from "node:assert/strict";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { installHarnessAlias, installHarnessWindow } from "./harness-alias.mjs";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
installHarnessWindow();
installHarnessAlias(root);
const local=await import(pathToFileURL(path.join(root,"src/lib/chat/localChatRead.ts")).href);
const pending=await import(pathToFileURL(path.join(root,"src/lib/chat/threadPending.ts")).href);
globalThis.localStorage.clear();
const old={id:"profile_u__anon_to__me",canonicalChatId:"profile_u__anon_to__me",lastMessage:"old own",lastMessageSender:"anon_me",latestSenderKind:"anon",latestMessageId:"old_1",anonSessionId:"anon_me",targetUid:"profile_owner",unreadCounts:{anon_me:1},readBy:{anon_me:false}};
const rendered={...old,lastMessage:"Te respondo",lastMessageSender:"profile_profile_owner",latestSenderKind:"profile",latestMessageId:"incoming_2"};
local.markChatReadLocally(rendered,"anon_me","");
const lagged={...rendered,latestMessageId:undefined,readBy:{anon_me:false},unreadCounts:{anon_me:1}};
const read=pending.computeThreadPendingForViewer(lagged,"","");
assert.equal(read.computedPending,false,"late recovery must not rebold: "+read.reason);
const exact={...rendered,readBy:{anon_me:false},unreadCounts:{anon_me:1}};
assert.equal(pending.computeThreadPendingForViewer(exact,"","").computedPending,false);
const sameTextNew={...rendered,latestMessageId:"incoming_3",unreadCounts:{anon_me:1},readBy:{anon_me:false}};
assert.equal(pending.computeThreadPendingForViewer(sameTextNew,"","").computedPending,true,"identical new reply must re-bold when ID changes");
console.log("PASS PROFILE_REPLY_READ_NOT_REBOLD: late metadata, exact receipt, identical new reply");