const assert=require("node:assert/strict");const fs=require("node:fs");
const route=fs.readFileSync("src/app/chat/[chatId]/page.tsx","utf8");
const ctx=fs.readFileSync("src/contexts/AnonMatchContext.tsx","utf8");
const inbox=fs.readFileSync("src/components/chats/AnonDirectInboxButton.tsx","utf8");
const bootstrap=fs.readFileSync("src/components/anonMatch/AnonMatchBootstrap.tsx","utf8");
const page=fs.readFileSync("src/components/anonMatch/AnonShuffleDirectPage.tsx","utf8");
const win=fs.readFileSync("src/components/anonMatch/AnonDirectChatWindow.tsx","utf8");
assert.match(route,/return <AnonShuffleDirectPage chatId=\{chatId\} \/>/,"asd uses standard page route");
assert.match(ctx,/router\.push\(\x60\/chat\/\$\{encodeURIComponent\(String\(json\.chatId\)\)\}\x60\)/,"card navigates");
assert.match(inbox,/if \(id\.startsWith\("asd_"\)\)/,"inbox navigates");
assert.match(bootstrap,/!pageDM && !persistentDM \? <AnonDirectChatWindow/,"no duplicate match overlay");
assert.match(page,/pageMode pageChatId=\{chatId\}/,"page owner");
assert.match(win,/data-anon-shuffle-standard-chat="1"/,"standard fullscreen");
assert.match(win,/data-chat-thread-header="1"/,"normal header");
assert.match(win,/data-chat-standard-intro="1"/,"normal intro");
assert.match(win,/pageMode=\{pageMode\}/,"reuses direct text/media engine");
assert.match(win,/if \(pageMode\) \{/,"page layout precedes compact modal");
assert.match(win,/router\.push\("\/chats"\)/,"back to Chats");
console.log("PASS FULL-PAGE SHUFFLE DM: card->standard chat page; Chats row->same route; match modal suppressed; normal layout and intro; same media, messages, reply, bomb engine; back to Chats.");
