import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
const root=process.cwd();
const mod=await import(pathToFileURL(path.join(root,"src/lib/shuffle/sharedPublicPoolCache.ts")).href);
const fixture=Array.from({length:646},(_,i)=>({uid:"user"+i,username:"Person_"+i,bio:"Hello ".repeat(15),photo:"https://example.com/avatar/"+i,flags:{moderation:false,banned:false}}));
const packed=mod.packSharedPool(fixture);
assert.ok(packed.length<800000,"snapshot must fit safely in 1 Firestore doc");
assert.deepEqual(mod.unpackSharedPool(packed),fixture);
assert.throws(()=>mod.unpackSharedPool("bad-blob"));
const now=Date.now();
assert.equal(mod.sharedPoolWithinAge(now-60_000,now,4*60_000),true);
assert.equal(mod.sharedPoolWithinAge(now-5*60_000,now,4*60_000),false);
assert.equal(mod.sharedPoolWithinAge(now+10,now,4*60_000),false);
const source=fs.readFileSync(path.join(root,"src/lib/shuffle/sharedPublicPoolCache.ts"),"utf8");
const route=fs.readFileSync(path.join(root,"src/app/api/shuffle/route.ts"),"utf8");
const rules=fs.readFileSync(path.join(root,"firestore.rules"),"utf8");
assert.match(source,/collection\("system"\)/);
assert.match(rules,/collection != 'system'/);
assert.match(source,/leaseUntilMs/);
assert.match(source,/directScan\(\)/);
assert.match(route,/if \(force\) return fetchProfilesUncached\(true\)/);
assert.match(route,/cachedProfilesAt = shared\.refreshedAtMs/);
assert.match(route,/getLiveShuffleVisitors\(false\)/);
assert.match(route,/profileIsVisibleToViewer/);
assert.match(route,/profileMatchesShuffleServerFilters/);
console.log("PASS SHUFFLE_SHARED_CACHE",JSON.stringify({profiles:fixture.length,compressedBytes:packed.length,staleLimitMinutes:10,sharedTtlMinutes:4,authCollection:"system"}));
