const assert=require("node:assert/strict");
const fs=require("node:fs");
const vm=require("node:vm");
const ts=require("typescript");
const route=fs.readFileSync("src/app/api/shuffle/route.ts","utf8");
const pool=fs.readFileSync("src/lib/anonMatch/matchPool.ts","utf8");
const client=fs.readFileSync("src/lib/shuffle/shuffleSlotsStore.ts","utf8");
const card=fs.readFileSync("src/components/modern/ModernShuffleCard.tsx","utf8");
const classic=fs.readFileSync("src/components/shuffle/ClassicShuffleProfileRow.tsx","utf8");
const raw=route.match(/function isAnonymousDocActive\(doc: any, now = Date\.now\(\)\) \{[\s\S]*?\n\}/);
assert.ok(raw,"Actual server visitor freshness predicate found");
const js=ts.transpileModule(raw[0],{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
const context={Date,Number,ANON_MATCH_PRESENCE_FRESH_MS:180000,fieldInstant:(f,k)=>Date.parse(f[k]||"")||0};
vm.createContext(context);
vm.runInContext(js+";this.check=isAnonymousDocActive;",context);
const now=Date.now();
const make=(age,extra={})=>({fields:{lastSeenAt:new Date(now-age).toISOString(),expiresAt:new Date(now+3600000).toISOString(),...extra}});
for(const age of [0,40000,147000,179000])assert.equal(context.check(make(age),now),true,"valid age "+age);
for(const age of [181000,600000,3386000])assert.equal(context.check(make(age),now),false,"stale lease "+age);
assert.equal(context.check(make(40000,{expiresAt:new Date(now-1).toISOString()}),now),false,"expired doc");
const source=fs.readFileSync("src/lib/shuffle/shuffleVisitorFresh.ts","utf8").replace(/^import .*;$/m,"const ANON_MATCH_PRESENCE_FRESH_MS=180000;");
const transformed=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const cjs={exports:{}};
vm.runInNewContext(transformed,{exports:cjs.exports,module:cjs,Date,Number});
const fresh=cjs.exports.isShuffleVisitorFresh;
assert.equal(fresh({shuffleVisitor:true,lastActive:new Date(now-147000).toISOString()},now),true);
assert.equal(fresh({shuffleVisitor:true,lastActive:new Date(now-3386000).toISOString()},now),false);
assert.equal(fresh({shuffleVisitor:false,lastActive:new Date(now-3386000).toISOString()},now),true);
assert.match(pool,/getAnonMatchAdminDoc\("anonimos_activos", targetId\)/,"no full pool for selected visitor");
assert.match(pool,/if \(pendingAnonIds\.has\(targetId\) \|\| busyAnonIds\.has\(targetId\)\) return null/);
assert.match(client,/isShuffleVisitorFresh\(profile, now\)/);
assert.match(card,/if \(!isShuffleVisitorFresh\(profile\)\) return null/);
assert.match(classic,/if \(!isShuffleVisitorFresh\(profile\)\) return null/);
console.log("PASS SHUFFLE REAL AVAILABILITY: server excludes 56m background ghost; 147s recent accepted; expired removed; client both designs guard; targeted exact doc with busy checks.");
