const fs=require("node:fs");
const assert=require("node:assert/strict");
const ts=require("typescript");
const vm=require("node:vm");
const helper=fs.readFileSync("src/lib/anonMatch/chatId.ts","utf8");
const out={exports:{}};
vm.runInNewContext(ts.transpileModule(helper,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:out.exports,module:out});
const id=out.exports.buildShuffleAnonDirectChatId;
const a="anon_TESTalpha123_abc987",b="anon_TESTbeta456_def123";
assert.equal(id(a,b),id(b,a),"same pair regardless caller ordering");
assert.notEqual(id(a,b),id(a,"anon_OTHER777_xyz123"));
assert.ok(id(a,b).startsWith("asd_"),"persistent direct chat prefix");
assert.throws(()=>id(a,a));
const route=fs.readFileSync("src/app/api/anon-match/shuffle-direct/route.ts","utf8");
assert.match(route,/verifyAnonMatchCaller\(req\)/);
assert.match(route,/assertAnonMatchAliasForCaller\(caller, body\.solicitanteAnonId\)/);
assert.match(route,/lookupAnonMatchAliasBinding\(targetAlias\)/);
assert.match(route,/createAnonMatchAdminDoc\("chats_anonimos",chatId/);
assert.match(route,/source:"shuffle_direct"/);
assert.match(route,/allowExistingChatsForDirectOpen: true/);
assert.doesNotMatch(route,/solicitudes_chat_anonimo|\/request\b/);
const ctx=fs.readFileSync("src/contexts/AnonMatchContext.tsx","utf8");
assert.match(ctx,/fetchAnonMatch\("\/api\/anon-match\/shuffle-direct"/);
assert.match(ctx,/await openDirectChat\(String\(json\.chatId\), "anonimo"\)/);
assert.match(ctx,/!previous\.chatId\.startsWith\("asd_"\) && !chatId\.startsWith\("asd_"\)/);
assert.match(ctx,/bridgeAnonDirectShellsToInboxChats/);
const pool=fs.readFileSync("src/lib/anonMatch/matchPool.ts","utf8");
assert.match(pool,/if \(row\.source === "shuffle_direct"\) continue/);
const service=fs.readFileSync("src/lib/anonMatch/service.ts","utf8");
assert.match(service,/row\.source !== "shuffle_direct"/);
console.log("PASS persistent anon Shuffle DM: auth alias binding, deterministic pair, immediate chat creation, GENERAL inbox bridge, no exclusive busy lock, old random flow isolated.");
